### ISSUE TITLE
Unable to pass the lint test after adding this

### ISSUE THREAD

**Issue by bhupendra-trustgrid** [alexvcasillas/react-native-loading-dots#3]
I'm using this react-native-loading-dots into my expo project which I've coded in Typescript, I've installed this library and its working fine, but when I'm checking the lint test then its failing.
 
React Native: 0.69.4
OS: Mac/Windows
Expo: ^46.0.0
react-native-loading-dots": "^1.3.0"

Output:
error TS7016: Could not find a declaration file for module 'react-native-loading-dots'. '..../node_modules/react-native-loading-dots/src/react-native-loading-dots.js' implicitly has an 'any' type.
  Try npm i --save-dev @types/react-native-loading-dots if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-loading-dots';`

import LoadingDots from 'react-native-loading-dots';

Expected Output: Should pass all the test.

**Comment by alexvcasillas** [comment]
Hi :)

Sorry for the late response. Did you still have this issue after declaring the module in a global `.d.ts` file? I'm not using TypeScript to create this module and therefore, there are no types. In order to solve your issue, you would need to do the following:

1. Create a `global.d.ts` file at the root of your project.
2. Include the following: `declare module "react-native-loading-dots";`

That should work and you should not have that linting error anymore. Sorry for the inconvenience of the late response 🙇🏻
